config/routes.rb
Railsforest::Application.routes.draw do
  
  resources :products do
  	resources :reviews, :except=>[:index]
  end

  resources :users, :only=>[:new, :create]
  resources :sessions, :only=>[:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews
	has_many :users, :through=>:reviews

	validates :description, :name, :price_in_cents, :presence=>true
	validates :price_in_cents, :numericality=>{:only_integer=>true}

	def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :product
	belongs_to :user

	validates :user, presence: true
	validates :product, presence: true
	validates :comment, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates_presence_of :name

	has_many :reviews
	has_many :products, :through=>:reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private
	def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
	def new
		@product = Product.new
	end

	def index
		@products = if params[:search]
			Product.where("name LIKE ?","%#{params[:search]}%")
		else
			Product.all.page(params[:page])
		end

		@products = @products.page(params[:page]).order("created_at DESC")

		respond_to do |format|
			format.html
			format.js
			format.json { render json: @products }
		end
	end

	def show
		@product = Product.find(params[:id])

		if current_user
			@review = @product.reviews.build
		end
	end

	def create
		@product = Product.new(product_params)

		if @product.save
			redirect_to products_url
		else
			render :new
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])

		if @product.update_attributes(product_params)
			redirect_to product_path(@product)
		else
			render :edit
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end

	private
	def product_params
		params.require(:product).permit(:name, :description, :price_in_cents)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :ensure_logged_in, :only=>[:edit, :create, :show, :destroy]
  before_filter :load_product

  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user_id = current_user.id

  # 	@review = Review.new(
  # 	:comment => params[:review][:comment],
  # 	:product_id => @product.id,
  # 	:user_id => current_user.id
  # )
		session[:return_to] ||= request.referer

		respond_to do |format|
			if @review.save
				format.html {redirect_to session.delete(:return_to), notice: 'Review created successfully'}
				format.js{}
			else
				format.html{ render 'products/show', alert: 'There was an error' }
				format.js
			end
		end
	end

	def destroy
		@review = Review.find(params[:id])
		@review.destroy
	end

	private
	def review_params
		params.require(:review).permit(:comment, :product_id)
	end

	def load_product
		@product = Product.find(params[:product_id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, :notice=>"Logged in!"
  	else
      flash.now[:alert] = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, :notice=>"Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url
  	else
  		render "new"
  	end
  end


  private
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsforest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:alert] %>
		<p id="alert"><%= flash[:alert] %></p>
	<% end %>
<%= link_to("Main Page", products_path) %>
<%= yield %>

	<p class="userinfo">
		<% if current_user %>
			Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method=>:delete %>
		<% else %>
			<%= link_to "Log in", new_session_path %> or <%= link_to "Sign Up", new_user_path %>
		<% end %>
	</p>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
			
			<ul>
			<% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
			</ul>

		</div>
	<% end %>


	<div class="field">
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %><br/>
		<%= f.text_field :description %>
	</div>
	<div class="field">
		<%= f.label :price_in_cents %><br/>
		<%= f.text_field :price_in_cents %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product.id) do %>
	<h2>
		<%= number_to_currency(product.formatted_price) %>
		<%= product.name %>
	</h2>
<% end %>

<p><%= truncate(product.description, length: 100) %></p>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Back', product_path %>

app/views/products/index.html.erb
<h1>Products</h1>
<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Search" %>
<% end %>

<p id="products-count"><%= page_entries_info @products %></p>

<div id="products">
	<%= render @products %>
</div>

<div id="products-pagination"><%= paginate @products %></div>

app/views/products/index.js.erb
$('#products').append("<%= j(render @products) %>");
$('#products-pagination').html("<%= j(paginate @products) %>");
$('#products-count').html("<% j(page_entries_info @products) %>");

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Edit - Delete</h2>


<p>
	<%= @product.name %><br/>
	<%= @product.description %><br/>
	<%= @product.formatted_price %><br/>
</p>

<%= link_to('Edit Product', edit_product_path(@product.id)) %> | <%= link_to('Delete This Product', @product, :confirm=>"Are you sure you want to delete this product?", :method=>:delete) %>


<% if current_user %>
	<h4>Write a review...</h4>

	<%= form_for([@product, @review], remote: true) do |f| %>
		<div id="review-form-errors">
			<% if @review.errors.any? %>
				<%= render 'reviews/errors' %>
			<% end %>
		</div>
	
	
		<div class="field">
			<%= f.label :comment %><br/>
			<%= f.text_area :comment %>
		</div>
		<div class="actions">
			<%= f.submit %>
		</div>
	<% end %>

	<p><b>Reviews for:</b> <%= @product.name %></p>

 	<div id="reviews-list">
		<% @product.reviews.each do |review| %>
			<% if review.id.present? %>
				<%= render partial: 'reviews/review', locals: {review: review} %>
			<% end %>
		<% end %>
	</div>

<% end %>

app/views/reviews/_errors.js.erb
<div id="error_explanations">
	<h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

	<ul>
		<% @review.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>

</div>

app/views/reviews/_review.html.erb
<div class="review">
	<p>
		<%= review.comment %>
		<br/>
		<% if review.user != nil %>
			<em>by <%=review.user.email %></em>
			Added on: <%=review.created_at %>
		<% end %>
	</p>
</div>

app/views/reviews/create.js.erb
<% if @review.errors.any? %>
	$('#review-form-errors').html("<%= j(render partial: 'errors') %>");
<% else %>
	$("#review-form-errors").html("");
	$('#reviews-list').append("<%= j(render partial: 'review', locals: {review: @review}) %>");
	$('#review_comment').val("");
<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>...Sorry, unsuccessful</h2>
			<ul>
				<% @user.errors.full_messages do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	
	<div class="field">
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</div>	
	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>	